name: playerChatMessages
version: '${project.version}'
main: com.mellurboo.playerchatmessages.PlayerChatMessages
api-version: '1.20'
commands:
  playerChatMessages.reload:
    description: Reloads config