name: reminders
version: '1.0'
main: com.mellurboo.reminders.Reminders
api-version: '1.20'
commands:
  reminders.reload:
    description: reloads the plugin
  blake:
    description: try
  store:
    description: shows webstore
