name: WardenMobDrop
version: '${project.version}'
main: com.mellurboo.wardenmobdrop.WardenMobDrop
api-version: '1.20'
commands:
  reloadWardenConfig:
    description: Reloads the config.yml file without restarting
    usage: /wardenReloadConfig
