#
# Myles "Mellurboo" Wilson 2023
#

# Mob Kill Exp Multiplier
expMultipler: 2

# Farming
expDroppedWhileFarming: 2
expDropChance: 50

# MVP GRANT
newMVPBAR: "§l§m§x§F§F§B§0§7§9-§x§F§F§B§3§7§A-§x§F§F§B§7§7§B-§x§F§F§B§A§7§C-§x§F§F§B§D§7§D-§x§F§F§C§1§7§D-§x§F§F§C§4§7§E-§x§F§F§C§7§7§F-§x§F§F§C§B§8§0-§x§F§F§C§E§8§1-§x§F§F§D§1§8§2-§x§F§F§D§5§8§3-§x§F§F§D§8§8§4-§x§F§F§D§9§8§4-§x§F§F§D§8§8§5-§x§F§F§D§8§8§5-§x§F§F§D§8§8§5-§x§F§F§D§7§8§6-§x§F§F§D§7§8§6-§x§F§F§D§7§8§6-§x§F§F§D§7§8§6-§x§F§F§D§6§8§7-§x§F§F§D§6§8§7-§x§F§F§D§6§8§7-§x§F§F§D§5§8§8-§x§F§F§D§4§8§7-§x§F§F§D§3§8§5-§x§F§F§D§1§8§3-§x§F§F§D§0§8§1-§x§F§F§C§E§7§F-§x§F§F§C§C§7§D-§x§F§F§C§B§7§B-§x§F§F§C§9§7§9-§x§F§F§C§7§7§7-§x§F§F§C§6§7§5-§x§F§F§C§4§7§3-§x§F§F§C§3§7§1-§x§F§F§C§1§6§F-"
newMVP: " §x§F§F§9§4§4§AH§x§F§F§9§A§4§Ca§x§F§F§9§F§4§Ds §x§F§F§A§5§4§Fs§x§F§F§A§B§5§0u§x§F§F§B§0§5§2p§x§F§F§B§6§5§3p§x§F§F§B§C§5§5o§x§F§F§C§2§5§6r§x§F§F§C§7§5§8t§x§F§F§C§B§5§9e§x§F§F§C§A§5§9d §x§F§F§C§A§5§9t§x§F§F§C§9§5§Ah§x§F§F§C§8§5§Ae §x§F§F§C§8§5§As§x§F§F§C§7§5§Ae§x§F§F§C§6§5§Br§x§F§F§C§6§5§Bv§x§F§F§C§5§5§Be§x§F§D§C§2§5§8r §x§F§B§B§D§5§3w§x§F§8§B§8§4§Ei§x§F§6§B§4§4§At§x§F§3§A§F§4§5h §x§F§1§A§A§4§0[§x§E§E§A§5§3§BM§x§E§C§A§1§3§7V§x§E§9§9§C§3§2P§x§E§7§9§7§2§D]"
rightArrows: "§x§F§F§9§4§4§A>§x§F§F§C§8§5§A>§x§E§7§9§7§2§D>§n"
leftArrows: " §x§F§F§9§4§4§A<§x§F§F§C§8§5§A<§x§E§7§9§7§2§D<"