name: MVPPerks
version: '1.0'
main: com.mellurboo.mvpperks.MVPPerks
api-version: '1.20'
permissions:
  MVPPerks.isMVP:
    description: is the player using a paid rank?
    default: false


commands:
  MVP.Reload:
    description: reloads the plugin config
  MVPGRANT:
    description: message display
  store:
    description: opens store