#
# Myles "Mellurboo" Wilson 2023
#

# Mob Kill Exp Multiplier
expMultipler: 2

# Farming
expDroppedWhileFarming: 1
expDropChance: 25

# MVP GRANT
newVIPBAR: "§x§3§2§B§B§8§4-§x§3§4§B§D§8§4-§x§3§6§B§F§8§5-§x§3§7§C§1§8§5-§x§3§9§C§2§8§6-§x§3§B§C§4§8§6-§x§3§D§C§6§8§7-§x§3§F§C§8§8§7-§x§4§0§C§A§8§8-§x§4§2§C§C§8§8-§x§4§4§C§D§8§9-§x§4§6§C§F§8§9-§x§4§8§D§1§8§A-§x§4§A§D§3§8§A-§x§4§B§D§5§8§A-§x§4§D§D§7§8§B-§x§4§F§D§8§8§B-§x§5§1§D§A§8§C-§x§5§3§D§C§8§C-§x§5§4§D§E§8§D-§x§5§6§E§0§8§D-§x§5§8§E§2§8§E-§x§5§A§E§3§8§E-§x§5§C§E§5§8§F-§x§5§D§E§7§8§F-§x§5§F§E§9§8§F-§x§6§1§E§B§9§0-§x§6§3§E§D§9§0-§x§6§5§E§E§9§1-§x§6§7§F§0§9§1-§x§6§8§F§2§9§2-§x§6§A§F§4§9§2-§x§6§C§F§6§9§3-§x§6§E§F§8§9§3-§x§7§0§F§9§9§4-§x§7§1§F§B§9§4-§x§7§3§F§D§9§5-§x§7§5§F§F§9§5-"
newVIP: "§x§3§2§B§B§8§4H§x§3§4§B§E§8§5a§x§3§7§C§0§8§5s §x§3§9§C§3§8§6s§x§3§C§C§5§8§7u§x§3§E§C§8§8§7p§x§4§1§C§A§8§8p§x§4§3§C§D§8§8o§x§4§6§C§F§8§9r§x§4§8§D§2§8§At§x§4§B§D§4§8§Ae§x§4§D§D§7§8§Bd §x§5§0§D§9§8§Ct§x§5§2§D§C§8§Ch§x§5§5§D§E§8§De §x§5§7§E§1§8§Ds§x§5§A§E§3§8§Ee§x§5§C§E§6§8§Fr§x§5§F§E§8§8§Fv§x§6§1§E§B§9§0e§x§6§4§E§D§9§1r §x§6§6§F§0§9§1w§x§6§9§F§2§9§2i§x§6§B§F§5§9§2t§x§6§E§F§7§9§3h §x§7§0§F§A§9§4V§x§7§3§F§C§9§4I§x§7§5§F§F§9§5P"
rightArrows: "§x§3§2§B§B§8§4>§x§5§4§D§D§8§D>§x§7§5§F§F§9§5>§n"
leftArrows: " §x§3§2§B§B§8§4<§x§5§4§D§D§8§D<§x§7§5§F§F§9§5<"