name: customJoinMessage
version: '${project.version}'
main: com.mellurboo.customjoinmessage.CustomJoinMessage
api-version: '1.20'
commands:
  reloadCustomJoinMessage:
    description: Reloads the Custom Join Message configuration
    usage: /reloadCustomJoinMessage
    permission: customjoinmessage.reloadconfig

