name: WardenMobDrop
version: '1.0'
main: com.mellurboo.wardenmobdrop.WardenMobDrop
api-version: '1.20'
commands:
  warden.reloadconfig:
    description: Reloads the config.yml file without restarting
