server-info:
  title: "Server Handbook"
  author: "Server Admin"
  pages:
    - "Welcome to the server!"
    - "Server Rules:"
    - "1. Be respectful."
    - "2. No griefing."
    - "3. Have fun!"
    - "Thank you for playing on our server!"