name: chumtpa
version: '1.0'
main: com.mellurboo.chumtpa.Chumtpa
api-version: '1.20'
commands:
  tpdeny:
    description: no tp
  tpaccept:
    description: accept a tpa
  tpa:
    description: tpa request
  tpreload:
    description: reloads the tpa config