#
# Myles "Mellurboo" Wilson
# Ava "LikesBread"
#

#
# For the MVP colors, use SimplyMC to make them gradiants (fucking great site btw)
# then just put them in the MVP varient
#

OwnerJoinMsg: "§x§C§7§6§B§F§FS§x§C§B§6§F§F§Fe§x§C§E§7§3§F§Fr§x§D§2§7§7§F§Fv§x§D§6§7§B§F§Fe§x§D§A§8§0§F§Fr §x§D§D§8§4§F§FO§x§E§1§8§8§F§Fw§x§E§5§8§C§F§Fn§x§E§8§9§0§F§Fe§x§E§C§9§4§F§Fr"
adminJoinMsg: "§x§F§F§7§1§7§1A§x§F§F§6§D§6§Dd§x§F§F§6§9§6§9m§x§F§F§6§5§6§5i§x§F§F§6§1§6§1n "

# playerJoin Message option
playerJoinMessages: [
  "what a shame,",
  "Hole dweller",
  "substance owner,",
  "Look out,",
  "BOO!",
  "cocan goblin,",
  "fake speedrunner,",
  "here they come",
  "scary",
  "Windows fanboy,",
  "TopG,",
  "Watch your wallets!",
  "reyna main",
  "unfortunatly...",
  "clueless",
  "YAY",
  "womp womp",
  "L",
  "deranking",
  "pisslo"
]

MVPplayerJoinMessages: [
  "§x§F§F§C§2§7§1w§x§F§F§B§F§6§Eh§x§F§F§B§D§6§Ba§x§F§F§B§A§6§7t §x§F§F§B§7§6§4a §x§F§F§B§5§6§1s§x§F§F§B§2§5§Eh§x§F§F§A§F§5§Ba§x§F§F§A§C§5§7m§x§F§F§A§A§5§4e§x§F§F§A§7§5§1,",
  "§x§F§F§C§2§7§1H§x§F§F§B§F§6§Eo§x§F§F§B§D§6§Bl§x§F§F§B§A§6§7e §x§F§F§B§7§6§4d§x§F§F§B§5§6§1w§x§F§F§B§2§5§Ee§x§F§F§A§F§5§Bl§x§F§F§A§C§5§7l§x§F§F§A§A§5§4e§x§F§F§A§7§5§1r",
  "§x§F§F§C§2§7§1s§x§F§F§C§0§6§Fu§x§F§F§B§E§6§Cb§x§F§F§B§C§6§As§x§F§F§B§A§6§8t§x§F§F§B§8§6§6a§x§F§F§B§6§6§3n§x§F§F§B§5§6§1c§x§F§F§B§3§5§Fe §x§F§F§B§1§5§Co§x§F§F§A§F§5§Aw§x§F§F§A§D§5§8n§x§F§F§A§B§5§6e§x§F§F§A§9§5§3r§x§F§F§A§7§5§1,",
  "§x§F§F§C§2§7§1L§x§F§F§B§E§6§Co§x§F§F§B§A§6§8o§x§F§F§B§6§6§3k §x§F§F§B§3§5§Fo§x§F§F§A§F§5§Au§x§F§F§A§B§5§6t§x§F§F§A§7§5§1,",
  "§x§F§F§C§2§7§1B§x§F§F§B§9§6§6O§x§F§F§B§0§5§CO§x§F§F§A§7§5§1!,",
  "§x§F§F§C§2§7§1c§x§F§F§C§0§6§Eo§x§F§F§B§D§6§Bc§x§F§F§B§B§6§8a§x§F§F§B§8§6§5n §x§F§F§B§6§6§2g§x§F§F§B§3§6§0o§x§F§F§B§1§5§Db§x§F§F§A§E§5§Al§x§F§F§A§C§5§7i§x§F§F§A§9§5§4n§x§F§F§A§7§5§1,",
  "§x§F§F§C§2§7§1f§x§F§F§C§0§6§Fa§x§F§F§B§E§6§Dk§x§F§F§B§D§6§Be §x§F§F§B§B§6§8s§x§F§F§B§9§6§6p§x§F§F§B§7§6§4e§x§F§F§B§5§6§2e§x§F§F§B§4§6§0d§x§F§F§B§2§5§Er§x§F§F§B§0§5§Cu§x§F§F§A§E§5§An§x§F§F§A§C§5§7n§x§F§F§A§B§5§5e§x§F§F§A§9§5§3r§x§F§F§A§7§5§1,",
  "§x§F§F§C§2§7§1h§x§F§F§C§0§6§Ee§x§F§F§B§D§6§Br§x§F§F§B§B§6§8e §x§F§F§B§8§6§5t§x§F§F§B§6§6§2h§x§F§F§B§3§6§0e§x§F§F§B§1§5§Dy §x§F§F§A§E§5§Ac§x§F§F§A§C§5§7o§x§F§F§A§9§5§4m§x§F§F§A§7§5§1e",
  "§x§F§F§C§2§7§1s§x§F§F§B§B§6§9c§x§F§F§B§5§6§1a§x§F§F§A§E§5§9r§x§F§F§A§7§5§1y",
  "§x§F§F§C§2§7§1W§x§F§F§C§0§6§Fi§x§F§F§B§E§6§Cn§x§F§F§B§C§6§Ad§x§F§F§B§A§6§7o§x§F§F§B§8§6§5w§x§F§F§B§6§6§2s §x§F§F§B§3§6§0f§x§F§F§B§1§5§Da§x§F§F§A§F§5§Bn§x§F§F§A§D§5§8b§x§F§F§A§B§5§6o§x§F§F§A§9§5§3y§x§F§F§A§7§5§1,",
  "§x§D§8§C§0§4§CT§x§E§C§D§2§5§5o§x§F§F§E§3§5§Ep§x§F§F§C§A§4§CG§x§F§F§B§1§3§9,",
  "§x§F§F§C§2§7§1W§x§F§F§C§0§6§Fa§x§F§F§B§F§6§Dt§x§F§F§B§D§6§Bc§x§F§F§B§B§6§9h §x§F§F§B§A§6§7y§x§F§F§B§8§6§5o§x§F§F§B§6§6§3u§x§F§F§B§5§6§1r §x§F§F§B§3§5§Fw§x§F§F§B§1§5§Da§x§F§F§A§F§5§Bl§x§F§F§A§E§5§9l§x§F§F§A§C§5§7e§x§F§F§A§A§5§5t§x§F§F§A§9§5§3s§x§F§F§A§7§5§1!",
  "§x§F§F§C§2§7§1r§x§F§F§B§F§6§De§x§F§F§B§B§6§9y§x§F§F§B§8§6§5n§x§F§F§B§5§6§1a §x§F§F§B§1§5§Dm§x§F§F§A§E§5§9a§x§F§F§A§A§5§5i§x§F§F§A§7§5§1n",
  "§x§F§F§C§2§7§1u§x§F§F§C§0§6§Fn§x§F§F§B§E§6§Cf§x§F§F§B§C§6§Ao§x§F§F§B§A§6§8r§x§F§F§B§8§6§6t§x§F§F§B§6§6§3u§x§F§F§B§5§6§1n§x§F§F§B§3§5§Fa§x§F§F§B§1§5§Ct§x§F§F§A§F§5§Al§x§F§F§A§D§5§8y§x§F§F§A§B§5§6.§x§F§F§A§9§5§3.§x§F§F§A§7§5§1.",
  "§x§F§F§C§2§7§1c§x§F§F§B§E§6§Cl§x§F§F§B§A§6§8u§x§F§F§B§6§6§3e§x§F§F§B§3§5§Fl§x§F§F§A§F§5§Ae§x§F§F§A§B§5§6s§x§F§F§A§7§5§1s",
  "§x§F§F§C§2§7§1Y§x§F§F§B§5§6§1A§x§F§F§A§7§5§1Y",
  "§x§F§F§C§2§7§1w§x§F§F§B§E§6§Co§x§F§F§B§A§6§8m§x§F§F§B§6§6§3p §x§F§F§B§3§5§Fw§x§F§F§A§F§5§Ao§x§F§F§A§B§5§6m§x§F§F§A§7§5§1p",
  "§x§F§F§C§2§7§1L",
  "§x§F§F§C§2§7§1d§x§F§F§B§F§6§De§x§F§F§B§B§6§9r§x§F§F§B§8§6§5a§x§F§F§B§5§6§1n§x§F§F§B§1§5§Dk§x§F§F§A§E§5§9i§x§F§F§A§A§5§5n§x§F§F§A§7§5§1g",
  "§x§F§F§C§2§7§1p§x§F§F§B§D§6§Bi§x§F§F§B§7§6§4s§x§F§F§B§2§5§Es§x§F§F§A§C§5§7l§x§F§F§A§7§5§1o"
]

# playerQuit Message option
playerQuitMessages: [
  "Finally",
  "What a pussy",
  "Combat log?",
  "freelo",
  "this is a nice color. anyway",
  "Peace control",
  "GGEZ",
  "that one person who thinks theyre part of the friend group",
  "Skibbidi toilet 69420",
  "(Willy watcher 9000)",
  "I think",
  "And keep the change you filthy animal"
]

MVPplayerQuitMessages: [
  "§x§D§8§C§0§4§CF§x§E§5§C§C§5§2i§x§F§2§D§7§5§8n§x§F§F§E§3§5§Ea§x§F§F§D§2§5§2l§x§F§F§C§2§4§5l§x§F§F§B§1§3§9y",
  "§x§D§8§C§0§4§CW§x§E§1§C§8§5§0h§x§E§9§D§0§5§4a§x§F§2§D§7§5§8t §x§F§B§D§F§5§Ca §x§F§F§D§D§5§Ap§x§F§F§D§2§5§2u§x§F§F§C§7§4§9s§x§F§F§B§C§4§1s§x§F§F§B§1§3§9y",
  "§x§D§8§C§0§4§CC§x§E§1§C§8§5§0o§x§E§9§D§0§5§4m§x§F§2§D§7§5§8b§x§F§B§D§F§5§Ca§x§F§F§D§D§5§At §x§F§F§D§2§5§2l§x§F§F§C§7§4§9o§x§F§F§B§C§4§1g§x§F§F§B§1§3§9?",
  "§x§D§8§C§0§4§Cf§x§E§8§C§E§5§3r§x§F§7§D§C§5§Ae§x§F§F§D§9§5§7e§x§F§F§C§5§4§8l§x§F§F§B§1§3§9o",
  "§x§D§8§C§0§4§Ct§x§D§C§C§3§4§Eh§x§D§F§C§6§4§Fi§x§E§3§C§A§5§1s §x§E§6§C§D§5§3i§x§E§A§D§0§5§4s §x§E§D§D§3§5§6a §x§F§1§D§6§5§7n§x§F§4§D§9§5§9i§x§F§8§D§D§5§Bc§x§F§B§E§0§5§Ce §x§F§F§E§3§5§Ec§x§F§F§D§E§5§Bo§x§F§F§D§A§5§7l§x§F§F§D§5§5§4o§x§F§F§D§1§5§1r§x§F§F§C§C§4§D. §x§F§F§C§8§4§Aa§x§F§F§C§3§4§6n§x§F§F§B§F§4§3y§x§F§F§B§A§4§0w§x§F§F§B§6§3§Ca§x§F§F§B§1§3§9y",
  "§x§D§8§C§0§4§CP§x§D§F§C§6§4§Fe§x§E§6§C§D§5§3a§x§E§D§D§3§5§6c§x§F§4§D§9§5§9e §x§F§B§E§0§5§Cc§x§F§F§D§E§5§Bo§x§F§F§D§5§5§4n§x§F§F§C§C§4§Dt§x§F§F§C§3§4§6r§x§F§F§B§A§4§0o§x§F§F§B§1§3§9l",
  "§x§D§8§C§0§4§CG§x§F§2§D§7§5§8G§x§F§F§D§2§5§2E§x§F§F§B§1§3§9Z",
  "§x§D§8§C§0§4§Ct§x§D§A§C§1§4§Dh§x§D§B§C§3§4§Ea§x§D§D§C§4§4§Et §x§D§F§C§6§4§Fo§x§E§0§C§7§5§0n§x§E§2§C§9§5§1e §x§E§4§C§A§5§1p§x§E§5§C§C§5§2e§x§E§7§C§D§5§3r§x§E§9§C§F§5§4s§x§E§A§D§0§5§4o§x§E§C§D§2§5§5n §x§E§E§D§3§5§6w§x§E§F§D§5§5§7h§x§F§1§D§6§5§7o §x§F§3§D§8§5§8t§x§F§4§D§9§5§9h§x§F§6§D§B§5§Ai§x§F§8§D§C§5§Bn§x§F§9§D§E§5§Bk§x§F§B§D§F§5§Cs §x§F§D§E§1§5§Dt§x§F§E§E§2§5§Eh§x§F§F§E§2§5§De§x§F§F§E§0§5§Cy§x§F§F§D§E§5§Ar§x§F§F§D§C§5§8e §x§F§F§D§9§5§7p§x§F§F§D§7§5§5a§x§F§F§D§5§5§4r§x§F§F§D§3§5§2t §x§F§F§D§1§5§1o§x§F§F§C§F§4§Ff §x§F§F§C§D§4§Dt§x§F§F§C§B§4§Ch§x§F§F§C§8§4§Ae §x§F§F§C§6§4§9f§x§F§F§C§4§4§7r§x§F§F§C§2§4§6i§x§F§F§C§0§4§4e§x§F§F§B§E§4§2n§x§F§F§B§C§4§1d §x§F§F§B§A§3§Fg§x§F§F§B§7§3§Er§x§F§F§B§5§3§Co§x§F§F§B§3§3§Bu§x§F§F§B§1§3§9p",
  "§x§D§8§C§0§4§CS§x§D§C§C§4§4§Ek§x§E§1§C§8§5§0i§x§E§5§C§C§5§2b§x§E§9§D§0§5§4b§x§E§E§D§3§5§6i§x§F§2§D§7§5§8d§x§F§6§D§B§5§Ai §x§F§B§D§F§5§Ct§x§F§F§E§3§5§Eo§x§F§F§D§D§5§Ai§x§F§F§D§8§5§6l§x§F§F§D§2§5§2e§x§F§F§C§D§4§Et §x§F§F§C§7§4§96§x§F§F§C§2§4§59§x§F§F§B§C§4§14§x§F§F§B§7§3§D2§x§F§F§B§1§3§90",
  "§x§D§8§C§0§4§C(§x§D§D§C§4§4§EW§x§E§1§C§8§5§0i§x§E§6§C§C§5§2l§x§E§A§D§0§5§4l§x§E§F§D§5§5§7y §x§F§4§D§9§5§9w§x§F§8§D§D§5§Ba§x§F§D§E§1§5§Dt§x§F§F§E§0§5§Cc§x§F§F§D§A§5§7h§x§F§F§D§4§5§3e§x§F§F§C§E§4§Fr §x§F§F§C§9§4§A9§x§F§F§C§3§4§60§x§F§F§B§D§4§20§x§F§F§B§7§3§D0§x§F§F§B§1§3§9)",
  "§x§D§8§C§0§4§CI §x§E§8§C§E§5§3t§x§F§7§D§C§5§Ah§x§F§F§D§9§5§7i§x§F§F§C§5§4§8n§x§F§F§B§1§3§9k",
  "§x§D§8§C§0§4§CA§x§D§B§C§2§4§Dn§x§D§D§C§5§4§Ed §x§E§0§C§7§5§0k§x§E§2§C§9§5§1e§x§E§5§C§C§5§2e§x§E§8§C§E§5§3p §x§E§A§D§0§5§4t§x§E§D§D§3§5§6h§x§E§F§D§5§5§7e §x§F§2§D§7§5§8c§x§F§5§D§A§5§9h§x§F§7§D§C§5§Aa§x§F§A§D§E§5§Cn§x§F§C§E§1§5§Dg§x§F§F§E§3§5§Ee §x§F§F§E§0§5§Cy§x§F§F§D§C§5§9o§x§F§F§D§9§5§7u §x§F§F§D§6§5§4f§x§F§F§D§2§5§2i§x§F§F§C§F§4§Fl§x§F§F§C§C§4§Dt§x§F§F§C§8§4§Ah§x§F§F§C§5§4§8y §x§F§F§C§2§4§5a§x§F§F§B§E§4§3n§x§F§F§B§B§4§0i§x§F§F§B§8§3§Em§x§F§F§B§4§3§Ba§x§F§F§B§1§3§9l"
]

# playerQuit Message option
playerDeathMessages: [
  "§cLMFAO",
  "§cGGEZ",
  "§cUtterly Shameful",
  "§cKeep inventory is not enabled buddy",
  "§cFF",
  "§cOpen your eyes kid",
  "§cHealth <= 0 = true",
  "§cthats peak...",
  "§c'is it hardcore?'",
  "§ckaput,",
  "§clag ->"
]

MVPplayerDeathMessages: [
  "§x§C§2§0§0§0§0L§x§9§B§0§0§0§0M§x§7§4§0§0§0§0F§x§8§3§0§0§0§0A§x§9§1§0§0§0§0O",
  "§x§C§2§0§0§0§0G§x§8§E§0§0§0§0G§x§7§E§0§0§0§0E§x§9§1§0§0§0§0Z",
  "§x§C§2§0§0§0§0U§x§B§7§0§0§0§0t§x§A§C§0§0§0§0t§x§A§1§0§0§0§0e§x§9§5§0§0§0§0r§x§8§A§0§0§0§0l§x§7§F§0§0§0§0y §x§7§4§0§0§0§0S§x§7§8§0§0§0§0h§x§7§C§0§0§0§0a§x§8§0§0§0§0§0m§x§8§5§0§0§0§0e§x§8§9§0§0§0§0f§x§8§D§0§0§0§0u§x§9§1§0§0§0§0l",
  "§x§C§2§0§0§0§0K§x§B§D§0§0§0§0e§x§B§7§0§0§0§0e§x§B§2§0§0§0§0p §x§A§C§0§0§0§0i§x§A§7§0§0§0§0n§x§A§2§0§0§0§0v§x§9§C§0§0§0§0e§x§9§7§0§0§0§0n§x§9§2§0§0§0§0t§x§8§C§0§0§0§0o§x§8§7§0§0§0§0r§x§8§1§0§0§0§0y §x§7§C§0§0§0§0i§x§7§7§0§0§0§0s §x§7§5§0§0§0§0n§x§7§7§0§0§0§0o§x§7§9§0§0§0§0t §x§7§B§0§0§0§0e§x§7§D§0§0§0§0n§x§7§F§0§0§0§0a§x§8§1§0§0§0§0b§x§8§3§0§0§0§0l§x§8§5§0§0§0§0e§x§8§7§0§0§0§0d §x§8§9§0§0§0§0b§x§8§B§0§0§0§0u§x§8§D§0§0§0§0d§x§8§F§0§0§0§0d§x§9§1§0§0§0§0y",
  "§x§C§2§0§0§0§0F§x§C§2§0§0§0§0F",
  "§x§C§2§0§0§0§0O§x§B§7§0§0§0§0p§x§A§C§0§0§0§0e§x§A§1§0§0§0§0n §x§9§5§0§0§0§0y§x§8§A§0§0§0§0o§x§7§F§0§0§0§0u§x§7§4§0§0§0§0r §x§7§8§0§0§0§0e§x§7§C§0§0§0§0y§x§8§0§0§0§0§0e§x§8§5§0§0§0§0s §x§8§9§0§0§0§0k§x§8§D§0§0§0§0i§x§9§1§0§0§0§0d",
  "§x§C§2§0§0§0§0H§x§B§6§0§0§0§0e§x§A§A§0§0§0§0a§x§9§E§0§0§0§0l§x§9§2§0§0§0§0t§x§8§6§0§0§0§0h §x§7§A§0§0§0§0<§x§7§6§0§0§0§0= §x§7§B§0§0§0§00 §x§7§F§0§0§0§0= §x§8§4§0§0§0§0t§x§8§8§0§0§0§0r§x§8§D§0§0§0§0u§x§9§1§0§0§0§0e",
  "§x§C§2§0§0§0§0t§x§B§4§0§0§0§0h§x§A§6§0§0§0§0a§x§9§7§0§0§0§0t§x§8§9§0§0§0§0s §x§7§B§0§0§0§0p§x§7§7§0§0§0§0e§x§7§C§0§0§0§0a§x§8§1§0§0§0§0k§x§8§6§0§0§0§0.§x§8§C§0§0§0§0.§x§9§1§0§0§0§0.",
  "§x§C§2§0§0§0§0§§x§B§8§0§0§0§0c§x§A§F§0§0§0§0'§x§A§5§0§0§0§0i§x§9§B§0§0§0§0s §x§9§1§0§0§0§0i§x§8§8§0§0§0§0t §x§7§E§0§0§0§0h§x§7§4§0§0§0§0a§x§7§8§0§0§0§0r§x§7§B§0§0§0§0d§x§7§F§0§0§0§0c§x§8§3§0§0§0§0o§x§8§6§0§0§0§0r§x§8§A§0§0§0§0e§x§8§D§0§0§0§0?§x§9§1§0§0§0§0'",
  "§x§C§2§0§0§0§0k§x§A§3§0§0§0§0a§x§8§4§0§0§0§0p§x§7§A§0§0§0§0u§x§8§5§0§0§0§0t§x§9§1§0§0§0§0,",
  "§x§C§2§0§0§0§0l§x§9§B§0§0§0§0a§x§7§4§0§0§0§0g §x§8§3§0§0§0§0-§x§9§1§0§0§0§0>"
]